### ISSUE TITLE
Annotation for Default Value

### ISSUE THREAD

**Issue by aymen94** [spring-projects/spring-session-data-mongodb#100]
during the creation of the schema, there is no notation that says "in the case of a null field or not present to assign them a default"
example:
 when I define a mongo scheme
```
new Schema({ 
    count: { type: Number, default: 0 }
});
```
I also want that when I don't pass the field the value of default appears in the object.

### Expected behavior

```
@DefaultValue(0)
int count;
```
### Actual behavior
every time I send the object I initialize the field to let me add in mongo.
```
@Field 
int count = 0;
```
I also accept changes or suggestions.

**Comment by gregturn** [comment]
Is this supposed to be for Spring Session MongoDB or Spring Data MongoDB?

**Comment by aymen94** [comment]
@gregturn is for Spring Data MongoDB

**Comment by gregturn** [comment]
Then you may wish to close this issue and visit jira.spring.io.

**Comment by aymen94** [comment]
https://jira.spring.io/browse/DATAMONGO-2350
