### ISSUE TITLE
Old session is not deleted when using JacksonMongoSessionConverter

### ISSUE THREAD

**Issue by finke-ba** [spring-projects/spring-session-data-mongodb#119]
Hi @gregturn!
After you fix  #116 I tried this with JacksonMongoSessionConverter instead of JdkMongoSessionConverter. After that the old session ceased to be deleted.

### Expected behavior
After logging out current SESSION cookie should be deleted when using JacksonMongoSessionConverter.

### Actual behavior
After logging out current SESSION still exist and accessible in DB when using JacksonMongoSessionConverter. And oridinalSessionId the same for all cookies.

### Steps to reproduce
Please check this example - https://github.com/finke-ba/webflux-logout-not-delete-session-example.
There is one assumption what could be causing an error - CustomJacksonMongoSessionConverter line 62. But when using this fix part of test http request stop working.

### Reactor Netty version
4.2.42.Final

### JVM version (e.g. `java -version`)
1.8.0_212, x86_64: "AdoptOpenJDK 8"

### OS version (e.g. `uname -a`)
Mac OS, Darwin Kernel Version 18.7.0

**Comment by gregturn** [comment]
This shouldn’t be hard to turn into a test. Just like #116, but with Jackson wired in.

**Comment by gregturn** [comment]
Indeed, I've confirmed the problem with a clone of the `MongoDbLogoutVerificationTest`.

**Comment by finke-ba** [comment]
Hi @gregturn! Is any estimates when it could be fixed?

**Comment by finke-ba** [comment]
Hi @rwinch, @vpavic, @jxblum!
Sorry for the direct ping, but maybe you could help with this issue?

**Comment by gregturn** [comment]
I'm not quite sure (yet) how to fix this. Since I'm backed up on Spring Data work, I haven't been able to tackle it.

Pull requests welcome!

**Comment by finke-ba** [comment]
Hi @gregturn! Could you please review PR #122 which related to this issue?

**Comment by finke-ba** [comment]
@gregturn thanks a lot!
