### ISSUE TITLE
Classloader issues with devtools

### ISSUE THREAD

**Issue by creusar** [spring-projects/spring-session-data-mongodb#15]
Following on #13, after declaring my session attribute Serializable, a class cast exception like this one occurs:

```
java.lang.ClassCastException: br.com.mercur.rel.model.Usuario cannot be cast to br.com.mercur.rel.model.Usuario
```

That doesn't maked any sense at first, class cast exception trying to cast to the same class. Searching a little bit, i got here: https://github.com/spring-projects/spring-boot/issues/3805. From the issue description: 

> This means that the value restored from session has a class defined by the system ClassLoader. The application itself loads the same class from Spring Boot's RestartClassLoader. Since the two classes are loaded from different ClassLoaders they cannot be cast from one to the other.

The docs from spring boot devtools have a section on this: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-known-restart-limitations

Looking at the code, the default constructor on JdkMongoSessionConverter uses the serializer/deserializer from Spring, wich seems to be the recommended one from the docs. 

Removing spring-boot-dev-tools from the classpath solves the problem. Is there any possibility to keep using dev-tools? It's features are a much appreciated help at developing.

**Comment by gregturn** [comment]
@creusar You might be able to test this out faster than I can. Does setting a `serialVersionUID` solve this issue?

If you put that value into the class, would the classloader decide the classes are identical, and operate?

See https://stackoverflow.com/questions/285793/what-is-a-serialversionuid-and-why-should-i-use-it

**Comment by gregturn** [comment]
In fact, if this solves the problem, I will augment the reference docs to recommend such a solution in this scenario.

**Comment by creusar** [comment]
Yes, would be easy to test it. As soon as I do it, would come back and leave a reply.

**Comment by creusar** [comment]
Doesn't solve the issue. It's all fine when the login page is displayed, but the exception is thrown when trying to save the new session with the added principal (the class with the serialVersionUID).

**Comment by gregturn** [comment]
Does both the class stored and the new class both possess the serialVersionUID?

**Comment by creusar** [comment]
The session store was empty for this test.

**Comment by gregturn** [comment]
My internal contacts tell me serialVersionUID doesn't help with this, and that rolling through classloaders makes them different classes. So best bet is for me to solve the issues with the Jackson serializer and make that available.

**Comment by creusar** [comment]
@gregturn do you have any news on this?

**Comment by gregturn** [comment]
Latest release has Jackson support. I’d give that a shot.

**Comment by wilkinsona** [comment]
The problem is that `JdkMongoSessionConverter` is using a `DeserializingConverter` with the wrong class loader. It should be using the same class loader as is used by the `BeanFactory` to load bean classes. This can be injected into a bean by implementing `BeanClassLoaderAware`. Please see [this issue](https://github.com/spring-projects/spring-session/issues/968) and the [fix](https://github.com/spring-projects/spring-session/commit/ffa1bca898108d5105beee82c88cb96ac0e7cc87) for inspiration.

**Comment by creusar** [comment]
@gregturn Thanks for the fix! :smile:
