### ISSUE TITLE
Unable to use JacksonMongoSessionConverter with Spring WebFlux

### ISSUE THREAD

**Issue by finke-ba** [spring-projects/spring-session-data-mongodb#33]
Hello! I'm trying to save WebSession in Mongo with reactive driver in Spring WebFlux project.
It works with default JdkMongoSessionConverter but failed with JacksonMongoSessionConverter. I have an exception:
`Caused by: java.lang.ClassNotFoundException: javax.servlet.http.Cookie`

Problem in WebJackson2Module class, it uses javax.servlet.http.Cookie:
```java
@Override
public void setupModule(SetupContext context) {
	SecurityJackson2Modules.enableDefaultTyping((ObjectMapper) context.getOwner());
	context.setMixInAnnotations(Cookie.class, CookieMixin.class);
...
```
And I have no javax.servlet dependencies and I can't have it in Spring WebFlux.

### Expected behavior
I could use JacksonMongoSessionConverter for Spring Session Data Mongodb with Spring WebFlux. 

### Actual behavior
I have an exception:
```
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/Cookie
...
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.Cookie
```

### Steps to reproduce
1) Create Spring WebFlux project
2) Configure Spring Security
3) Add dependencies spring-boot-starter-data-mongodb-reactive and spring-session-data-mongodb
4) Configure Spring Session (spring.session.store-type=mongodb)
5) Add JacksonMongoSessionConverter bean:
```java
@Bean
public AbstractMongoSessionConverter mongoSessionConverter() {
   return new JacksonMongoSessionConverter();
}
```

### Reactor Netty version
I'm using SpringBoot 2.0.4.RELEASE with spring-boot-starter-webflux.
So version of Reactor Netty is 0.7.8.RELEASE.

### JVM version (e.g. `java -version`)
Java 10

### OS version (e.g. `uname -a`)
MacOS High Sierra 10.13.6

**Comment by gregturn** [comment]
Okay, I just reproduced this in the Spring Session MongoDB examples. Thanks.

**Comment by gregturn** [comment]
I opened https://github.com/spring-projects/spring-security/issues/5623 to so hopefully we can fix this in Spring Security.

**Comment by finke-ba** [comment]
Great, thank you!

**Comment by finke-ba** [comment]
Hello, @gregturn! Seems that issue could be closed as spring-projects/spring-security#5623 fixed problem with `javax.servlet.http.Cookie`.

**Comment by finke-ba** [comment]
Yes, that works for me, thanks!
So now I have to wait until all these changes fall into the spring boot.

**Comment by gregturn** [comment]
I'm going to close this for now. If you continue to see issues, please let me know.
