### ISSUE TITLE
2.0.3.RELEASE is not available in Maven Central

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session-data-mongodb#39]
According to [releases page](https://github.com/spring-projects/spring-session-data-mongodb/releases) and [Spring `libs-release` repo](https://repo.spring.io/libs-release/org/springframework/session/spring-session-data-mongodb/2.0.3.RELEASE/), the `2.0.3.RELEASE` was released on August 2nd however it apparently hasn't made it's way to [Maven Central](https://search.maven.org/search?q=g:org.springframework.session%20AND%20a:spring-session-data-mongodb&core=gav).

**Comment by gregturn** [comment]
Released.
