### ISSUE TITLE
Release 2.1.0.RELEASE

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session-data-mongodb#45]
Spring Session Bean is scheduled for release on Oct 25th. For spring-session-data-mongodb 2.1.0 to be included, we need a the GA release by Oct 24th. If it is not available, we will need to roll back to the previous GA of spring-session-data-monogodb in order to ensure Spring Session Bean gets in Spring Boot

**Comment by vpavic** [comment]
This appears to be done judging by spring-projects/spring-session-bom#30.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-session-data-mongodb/commit/2578107568f5e0f1c6aa9c2ef0830986c69c3d7c.
