### ISSUE TITLE
Rework @Configuration class that users may subclass to indicate whether or not they require proxying

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-session-data-mongodb#60]
This is related to https://github.com/spring-projects/spring-session/issues/1345.

It would be beneficial if `@Configuration` classes that are intended to be sub-classed by users could be annotated with `@Configuration(proxyBeanMethods=false)` to indicate that they do not require proxying. If there are configuration classes where proxying is required (due to inter-dependent `@Bean` methods) it would be beneficial if they were reworked so that proxying is no longer required.

**Comment by gregturn** [comment]
Thanks @wilkinsona. When we upgrade to Spring Framework 5.2, we'll be able to consider it.
