### ISSUE TITLE
Add expiration to MongoSession to autodelete

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-session-data-mongodb#9]
Provide ability to automatically delete `MongoSession` documents.

Per Christoph: "You’d use `Index#expire(long, TimeUnit)` when creating the index manually via `IndexOperations#ensureIndex(IndexDefinition`."

**Comment by jkubrynski** [comment]
I believe this option exists. The problem is with the #53

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-session-data-mongodb/commit/82cf365ba702d569013ce83940a6000933cfd3b6.
